# frozen_string_literal: true

#
# Sentry SDK Configuration
# ========================
# Auto-generated by Error Observability Client Kit.
#
# For Rails: Place in config/initializers/sentry.rb
# For other apps: require this file in your entry point
#

require 'sentry-ruby'

dsn = ENV.fetch('SENTRY_DSN', '{{DSN}}')

if dsn.nil? || dsn.empty? || dsn == '{{DSN}}'
  warn 'Warning: SENTRY_DSN not configured'
else
  Sentry.init do |config|
    config.dsn = dsn
    config.environment = ENV.fetch('SENTRY_ENVIRONMENT', '{{ENVIRONMENT}}')
    config.release = ENV['APP_VERSION']

    # Performance Monitoring - adjust for production
    config.traces_sample_rate = ENV.fetch('SENTRY_TRACES_SAMPLE_RATE', '0.1').to_f

    # Data Settings
    config.send_default_pii = false
    config.max_breadcrumbs = 50
  end

  # Set default tags
  Sentry.set_tags(
    'app.component' => 'backend',
    'app.runtime' => 'ruby'
  )
end
