/**
 * Sentry SDK Configuration
 * ========================
 * Auto-generated by Error Observability Client Kit.
 *
 * For ASP.NET Core: builder.WebHost.UseSentry();
 * For Console Apps: SentryConfig.Init();
 */

using System;
using Sentry;

public static class SentryConfig
{
    private static IDisposable? _sentryDisposable;

    /// <summary>
    /// Initialize Sentry SDK.
    /// Call this once at application startup.
    /// </summary>
    public static void Init()
    {
        var dsn = Environment.GetEnvironmentVariable("SENTRY_DSN") ?? "{{DSN}}";

        if (string.IsNullOrEmpty(dsn) || dsn == "{{DSN}}")
        {
            Console.Error.WriteLine("Warning: SENTRY_DSN not configured");
            return;
        }

        _sentryDisposable = SentrySdk.Init(options =>
        {
            options.Dsn = dsn;
            options.Environment = Environment.GetEnvironmentVariable("SENTRY_ENVIRONMENT") ?? "{{ENVIRONMENT}}";
            options.Release = Environment.GetEnvironmentVariable("APP_VERSION");

            // Performance Monitoring - adjust for production
            var sampleRate = Environment.GetEnvironmentVariable("SENTRY_TRACES_SAMPLE_RATE");
            options.TracesSampleRate = !string.IsNullOrEmpty(sampleRate)
                ? double.Parse(sampleRate)
                : 0.1;

            // Data Settings
            options.SendDefaultPii = false;
            options.MaxBreadcrumbs = 50;
            options.AttachStacktrace = true;
        });

        // Set default tags
        SentrySdk.ConfigureScope(scope =>
        {
            scope.SetTag("app.component", "backend");
            scope.SetTag("app.runtime", "dotnet");
        });
    }

    /// <summary>
    /// Dispose Sentry SDK.
    /// Call this on application shutdown.
    /// </summary>
    public static void Dispose()
    {
        _sentryDisposable?.Dispose();
    }
}
