/**
 * Sentry SDK Configuration
 * ========================
 * Auto-generated by Error Observability Client Kit.
 *
 * Import this file at the TOP of your entry point:
 *   import './sentry.config';
 */

import * as Sentry from "@sentry/node";

const dsn = process.env.SENTRY_DSN || "{{DSN}}";

if (!dsn || dsn === "{{DSN}}") {
  console.warn("Warning: SENTRY_DSN not configured");
} else {
  Sentry.init({
    dsn: dsn,
    environment: process.env.SENTRY_ENVIRONMENT || "{{ENVIRONMENT}}",
    release: process.env.APP_VERSION,

    // Performance Monitoring - adjust for production
    tracesSampleRate: parseFloat(process.env.SENTRY_TRACES_SAMPLE_RATE || "0.1"),

    // Data Settings
    sendDefaultPii: false,
    maxBreadcrumbs: 50,
    attachStacktrace: true,
  });

  // Set default tags
  Sentry.setTag("app.component", "backend");
  Sentry.setTag("app.runtime", "nodejs");
  Sentry.setTag("app.language", "typescript");
}

export default Sentry;
