<?php
/**
 * Sentry SDK Configuration
 * ========================
 * Auto-generated by Error Observability Client Kit.
 *
 * Include this file in your bootstrap:
 *   require_once 'config/sentry.php';
 */

use Sentry\State\Scope;
use function Sentry\init;
use function Sentry\configureScope;

$dsn = getenv('SENTRY_DSN') ?: '{{DSN}}';

if (empty($dsn) || $dsn === '{{DSN}}') {
    error_log('Warning: SENTRY_DSN not configured');
    return;
}

init([
    'dsn' => $dsn,
    'environment' => getenv('SENTRY_ENVIRONMENT') ?: '{{ENVIRONMENT}}',
    'release' => getenv('APP_VERSION') ?: null,

    // Performance Monitoring - adjust for production
    'traces_sample_rate' => (float)(getenv('SENTRY_TRACES_SAMPLE_RATE') ?: 0.1),

    // Data Settings
    'send_default_pii' => false,
    'max_breadcrumbs' => 50,
    'attach_stacktrace' => true,
]);

// Set default tags
configureScope(function (Scope $scope): void {
    $scope->setTag('app.component', 'backend');
    $scope->setTag('app.runtime', 'php');
});
