/*
Sentry SDK Configuration
========================
Auto-generated by Error Observability Client Kit.

Usage:
  import "your-module/pkg/sentry"

  func main() {
      sentry.Init()
      defer sentry.Flush()
      // ...
  }
*/

package sentry

import (
	"fmt"
	"os"
	"strconv"
	"time"

	"github.com/getsentry/sentry-go"
)

// Init initializes the Sentry SDK.
// Call this once at application startup.
func Init() error {
	dsn := os.Getenv("SENTRY_DSN")
	if dsn == "" {
		dsn = "{{DSN}}"
	}

	if dsn == "{{DSN}}" {
		fmt.Fprintln(os.Stderr, "Warning: SENTRY_DSN not configured")
		return nil
	}

	environment := os.Getenv("SENTRY_ENVIRONMENT")
	if environment == "" {
		environment = "{{ENVIRONMENT}}"
	}

	tracesSampleRate := 0.1
	if rate := os.Getenv("SENTRY_TRACES_SAMPLE_RATE"); rate != "" {
		if parsed, err := strconv.ParseFloat(rate, 64); err == nil {
			tracesSampleRate = parsed
		}
	}

	err := sentry.Init(sentry.ClientOptions{
		Dsn:              dsn,
		Environment:      environment,
		Release:          os.Getenv("APP_VERSION"),
		TracesSampleRate: tracesSampleRate,
		AttachStacktrace: true,
	})

	if err != nil {
		return fmt.Errorf("sentry initialization failed: %w", err)
	}

	// Set default tags
	sentry.ConfigureScope(func(scope *sentry.Scope) {
		scope.SetTag("app.component", "backend")
		scope.SetTag("app.runtime", "go")
	})

	return nil
}

// Flush flushes pending events.
// Call this with defer in main().
func Flush() {
	sentry.Flush(5 * time.Second)
}

// CaptureException captures an exception.
func CaptureException(err error) {
	sentry.CaptureException(err)
}

// CaptureMessage captures a message.
func CaptureMessage(message string) {
	sentry.CaptureMessage(message)
}
