/**
 * Sentry SDK Configuration
 * ========================
 * Auto-generated by Error Observability Client Kit.
 *
 * Call SentryConfig.init() in your main method.
 */

import io.sentry.Sentry;

public class SentryConfig {

    private static boolean initialized = false;

    /**
     * Initialize Sentry SDK.
     * Call this once at application startup.
     */
    public static void init() {
        if (initialized) {
            return;
        }

        String dsn = System.getenv("SENTRY_DSN");
        if (dsn == null || dsn.isEmpty()) {
            dsn = "{{DSN}}";
        }

        if (dsn.equals("{{DSN}}")) {
            System.err.println("Warning: SENTRY_DSN not configured");
            return;
        }

        final String finalDsn = dsn;

        Sentry.init(options -> {
            options.setDsn(finalDsn);
            options.setEnvironment(
                System.getenv("SENTRY_ENVIRONMENT") != null
                    ? System.getenv("SENTRY_ENVIRONMENT")
                    : "{{ENVIRONMENT}}"
            );
            options.setRelease(System.getenv("APP_VERSION"));

            // Performance Monitoring - adjust for production
            String sampleRate = System.getenv("SENTRY_TRACES_SAMPLE_RATE");
            options.setTracesSampleRate(
                sampleRate != null ? Double.parseDouble(sampleRate) : 0.1
            );

            // Data Settings
            options.setSendDefaultPii(false);
            options.setMaxBreadcrumbs(50);
            options.setAttachStacktrace(true);
        });

        // Set default tags
        Sentry.setTag("app.component", "backend");
        Sentry.setTag("app.runtime", "java");

        initialized = true;
    }
}
