"""
Sentry SDK Configuration
========================
Auto-generated by Error Observability Client Kit.
"""

import os
import sentry_sdk


def init_sentry():
    """
    Initialize Sentry SDK.
    Call this once at application startup, before any other code.
    """
    dsn = os.getenv("SENTRY_DSN", "{{DSN}}")

    if not dsn or dsn == "{{DSN}}":
        print("Warning: SENTRY_DSN not configured")
        return

    sentry_sdk.init(
        dsn=dsn,
        environment=os.getenv("SENTRY_ENVIRONMENT", "{{ENVIRONMENT}}"),
        release=os.getenv("APP_VERSION"),

        # Performance Monitoring - adjust for production
        traces_sample_rate=float(os.getenv("SENTRY_TRACES_SAMPLE_RATE", "0.1")),

        # Data Settings
        send_default_pii=False,
        max_breadcrumbs=50,
        attach_stacktrace=True,
    )

    # Set default tags
    sentry_sdk.set_tag("app.component", "backend")


# Auto-initialize if this file is imported
# Comment out if you want to control initialization manually
# init_sentry()
